name: Coding standard refactor

on:
  schedule:
    - cron: "0 2 * * MON" # Run at 2am every Monday
  workflow_dispatch: ~

jobs:
  coding-standard:
    runs-on: ubuntu-latest
    name: "Coding standard refactor"

    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        branch: [ '4.0' ]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install PHP dependencies
        run: composer update --no-interaction --no-scripts

      - name: Run ECS
        run: vendor/bin/ecs check --fix src

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: '[CS] Refactor'
          author: CORS GmbH <office@cors.gmbh>
          title: '[CS] Refactor'
          body: |
            This PR has been generated automatically to fix code-styles
          labels: |
            Enhancement
          branch: coding-standard/refactor-${{ matrix.branch }}
          delete-branch: true
          base: ${{ matrix.branch }}